!$LIB_BASE?="https://raw.githubusercontent.com/sidneydemoraes/libs-plantuml/main"
!include $LIB_BASE/common.puml

!global $EVENT_BG_COLOR?="Orange"
!global $COMMAND_BG_COLOR?="MediumTurquoise"

left to right direction 

!procedure Event($id, $name="", $originCommandId="")
  Card($id, rectangle, DomainEvent, $name)
  !if ($originCommandId != "")
    $originCommandId --> $id
  !endif
!endprocedure

skinparam rectangle<<DomainEvent>> {
  BackgroundColor $EVENT_BG_COLOR
  FontColor $FONT_COLOR
}

!procedure Command($id, $name="")
  Card($id, rectangle,Command,$name)
!endprocedure 

skinparam rectangle<<Command>> {
  BackgroundColor $COMMAND_BG_COLOR
  FontColor $FONT_COLOR
}